### ISSUE TITLE
Gradle fails with java.lang.InternalError: stream error

### ISSUE THREAD

**Issue by felipecsl** [openjdk/aarch64-port#8]
Running Gradle v6.5 on [this early access build](https://github.com/microsoft/openjdk-aarch64/releases/tag/16-ea%2B10-macos) results in InternalError: stream error
```
Caused by: java.lang.InternalError: stream error
	at org.apache.tools.zip.ZipOutputStream.deflate(ZipOutputStream.java:1045)
	at org.apache.tools.zip.ZipOutputStream.flushDeflater(ZipOutputStream.java:588)
	at org.apache.tools.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:545)
	at org.gradle.internal.classpath.ClasspathBuilder$ZipEntryBuilder.put(ClasspathBuilder.java:88)
	at org.gradle.api.internal.runtimeshaded.RuntimeShadedJarCreator.processClassFile(RuntimeShadedJarCreator.java:219)
	at org.gradle.api.internal.runtimeshaded.RuntimeShadedJarCreator.processEntry(RuntimeShadedJarCreator.java:133)
	at org.gradle.api.internal.runtimeshaded.RuntimeShadedJarCreator.lambda$processFiles$1(RuntimeShadedJarCreator.java:97)
	at org.gradle.internal.classpath.ClasspathWalker.visitJarContents(ClasspathWalker.java:88)
	at org.gradle.internal.classpath.ClasspathWalker.visit(ClasspathWalker.java:52)
	at org.gradle.api.internal.runtimeshaded.RuntimeShadedJarCreator.processFiles(RuntimeShadedJarCreator.java:97)
	at org.gradle.api.internal.runtimeshaded.RuntimeShadedJarCreator.lambda$createFatJar$0(RuntimeShadedJarCreator.java:87)
	at org.gradle.internal.classpath.ClasspathBuilder.buildJar(ClasspathBuilder.java:58)
	at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:45)
	at org.gradle.api.internal.runtimeshaded.RuntimeShadedJarCreator.createFatJar(RuntimeShadedJarCreator.java:87)
	at org.gradle.api.internal.runtimeshaded.RuntimeShadedJarCreator.create(RuntimeShadedJarCreator.java:80)
	at org.gradle.api.internal.runtimeshaded.RuntimeShadedJarFactory$1.run(RuntimeShadedJarFactory.java:61)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.runtimeshaded.RuntimeShadedJarFactory.lambda$get$0(RuntimeShadedJarFactory.java:52)
	at org.gradle.cache.internal.DefaultGeneratedGradleJarCache$1.run(DefaultGeneratedGradleJarCache.java:62)
	at org.gradle.internal.Factories$1.create(Factories.java:26)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:220)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:201)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:192)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:216)
	at org.gradle.cache.internal.DefaultGeneratedGradleJarCache.get(DefaultGeneratedGradleJarCache.java:58)
	at org.gradle.api.internal.runtimeshaded.RuntimeShadedJarFactory.get(RuntimeShadedJarFactory.java:52)
	at org.gradle.api.internal.notations.DependencyClassPathNotationConverter.relocatedDepsJar(DependencyClassPathNotationConverter.java:161)
	at org.gradle.api.internal.notations.DependencyClassPathNotationConverter.gradleApiFileCollection(DependencyClassPathNotationConverter.java:128)
	at org.gradle.api.internal.notations.DependencyClassPathNotationConverter.access$100(DependencyClassPathNotationConverter.java:53)
	at org.gradle.api.internal.notations.DependencyClassPathNotationConverter$1.generateFileCollection(DependencyClassPathNotationConverter.java:96)
	at org.gradle.api.internal.notations.DependencyClassPathNotationConverter$GeneratedFileCollection.visitContents(DependencyClassPathNotationConverter.java:186)
	at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeFileCollection.java:145)
	at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:56)
	at org.gradle.api.internal.artifacts.dependencies.DefaultSelfResolvingDependency.resolve(DefaultSelfResolvingDependency.java:86)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProviderKt$gradleApiJarsProviderFor$1.invoke(KotlinScriptClassPathProvider.kt:214)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProviderKt$gradleApiJarsProviderFor$1.invoke(KotlinScriptClassPathProvider.kt)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider$gradleApi$2.invoke(KotlinScriptClassPathProvider.kt:113)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider$gradleApi$2.invoke(KotlinScriptClassPathProvider.kt:94)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider.getGradleApi(KotlinScriptClassPathProvider.kt)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider.access$getGradleApi$p(KotlinScriptClassPathProvider.kt:94)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider$gradleKotlinDsl$2.invoke(KotlinScriptClassPathProvider.kt:108)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider$gradleKotlinDsl$2.invoke(KotlinScriptClassPathProvider.kt:94)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider.getGradleKotlinDsl(KotlinScriptClassPathProvider.kt)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider.computeCompilationClassPath(KotlinScriptClassPathProvider.kt:146)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider.access$computeCompilationClassPath(KotlinScriptClassPathProvider.kt:94)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider$compilationClassPathOf$1.invoke(KotlinScriptClassPathProvider.kt:142)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider$compilationClassPathOf$1.invoke(KotlinScriptClassPathProvider.kt:94)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProviderKt$sam$java_util_function_Function$0.apply(KotlinScriptClassPathProvider.kt)
	at org.gradle.kotlin.dsl.provider.KotlinScriptClassPathProvider.compilationClassPathOf(KotlinScriptClassPathProvider.kt:142)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.compilationClassPathOf(KotlinScriptEvaluator.kt:272)
	at org.gradle.kotlin.dsl.execution.Interpreter$emitSpecializedProgramFor$cachedDir$1.invoke(Interpreter.kt:285)
	at org.gradle.kotlin.dsl.execution.Interpreter$emitSpecializedProgramFor$cachedDir$1.invoke(Interpreter.kt:66)
	at org.gradle.kotlin.dsl.cache.ScriptCache.initializeCacheDir(ScriptCache.kt:114)
	at org.gradle.kotlin.dsl.cache.ScriptCache.access$initializeCacheDir(ScriptCache.kt:37)
	at org.gradle.kotlin.dsl.cache.ScriptCache$cacheDirFor$1.execute(ScriptCache.kt:60)
	at org.gradle.kotlin.dsl.cache.ScriptCache$cacheDirFor$1.execute(ScriptCache.kt:37)
	at org.gradle.cache.internal.DefaultPersistentDirectoryCache$Initializer.initialize(DefaultPersistentDirectoryCache.java:100)
	at org.gradle.cache.internal.FixedSharedModeCrossProcessCacheAccess$1.run(FixedSharedModeCrossProcessCacheAccess.java:86)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:215)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:205)
	at org.gradle.cache.internal.FixedSharedModeCrossProcessCacheAccess.open(FixedSharedModeCrossProcessCacheAccess.java:83)
	at org.gradle.cache.internal.DefaultCacheAccess.open(DefaultCacheAccess.java:139)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:78)
```

Command executed: `./gradlew`

```
$ java -version
openjdk version "16" 2020-11-11
OpenJDK Runtime Environment Microsoft (build 16+10-20201111)
OpenJDK 64-Bit Server VM Microsoft (build 16+10-20201111, mixed mode)
```

**Comment by AntonKozlov** [comment]
According to log file, the problem likely relates to the processed zip file. It may happen that it's corrupted zip file somewhere on the filesystem. I suggest to clean up gradle caches or try on different arm64 machine. Just in case I've tried to run gradle daemon on that build, successfully.

**Comment by felipecsl** [comment]
Later I learned that it's actually a Gradle limitation, tracked here https://github.com/gradle/gradle/issues/13481. Closing this.
